name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install tools
        run: sudo apt-get install valgrind meson

      - name: make
        run: make
      - name: make check
        run: make check
